baseURL = 'https://nefko.xyz/'
languageCode = 'en-us'
title = 'Kyle Becker'
theme = 'nefkoPortfolio'
enableRobotsTXT = true


[params]
mainSections = ["blog", "case-studies"]
images = ["/images/og-default.png"]

[params.nefkoPortfolio.home]
content_alignment = "left"

# ------------------------------------------------------------
# GLOBAL NAV BAR -------------------
[[menu.main]]
  name = "What is UX Strategy?"
  pageRef = "/pages/experience-strategy"
  weight = 10

[[menu.main]]
  name = "Contact"
  pageRef = "/pages/contact"
  weight = 20