baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kyle Becker'
theme = 'nefkoPortfolio'


[params]
mainSections = ["blog", "case-studies"]

# ------------------------------------------------------------
# GLOBAL NAV BAR -------------------
[[menu.main]]
  name = "What is UX Strategy?"
  pageRef = "/pages/experience-strategy"
  weight = 10

[[menu.main]]
  name = "Contact"
  pageRef = "/pages/contact"
  weight = 20